### ISSUE TITLE
Orchard-Base-Theme shouldn't lock on every page load (OSOE-415)

### ISSUE THREAD

**Issue by sarahelsaig** [Lombiq/Orchard-Base-Theme#41]
> So we're overriding a resource used on the admin from the theme. This is not something we should do. Especially that we shouldn't update that Bootstrap version independently of Orchard, since all of the built-in Orchard admin features depend on the Bootstrap version provided by Orchard.
>
> So, I don't think overriding the Bootstrap resource for the admin theme is a valid use-case. If certain built-in widgets do that for the frontend, then a better approach is to override those specific shapes instead.

See [this issue](https://github.com/Lombiq/Orchard-Base-Theme/pull/40#discussion_r1003440757)

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-415)

**Comment by Piedone** [comment]
I'm not saying that we should use the built-in Bootstrap in this project. Rather, this theme shouldn't override resources on the admin.

In this, `RemoveBootstrap5()` should be removed.

**Comment by sarahelsaig** [comment]
Did more in-depth investigation and I have no idea what I was referring to. There are no resources are overridden to or from the admin. Maybe I confused it with a similar problem we had in the OCC repo.

To better explain the reason why we have to remove Bootstrap, it's about other modules that reference the "bootstrap" resource but don't depend on Orchard-Base-Theme. For example Orchard-Data-Tables does it [here](https://github.com/Lombiq/Orchard-Data-Tables/blob/3198a8603201649b93b981f18fe7e37498c481c8/Lombiq.DataTables/ResourceManagementOptionsConfiguration.cs#L61). So if your page contains a DataTable then the built-in resource gets injected and you have duplicate style sheets for that page. This applies to other third party resources as well.

On the other hand I've managed to avoid `lock`ing on every page load. Now the removal only happens once per process. After that it's just a simple bool check so basically no overhead.

**Comment by Piedone** [comment]
I see, OK then. Please document in the code why we're doing this, then.
