### ISSUE TITLE
The base theme doesn't enable Lombiq.HelpfulExtension (OSOE-622)

### ISSUE THREAD

**Issue by sarahelsaig** [Lombiq/Orchard-Base-Theme#65]
It should have "Lombiq Helpful Extensions - Helpful Widgets" as its dependency, because right now you have to enable it manually.

Also the "Lombiq Orchard Core Base Theme - Layers and Zones" recipe should run once if a Lombiq.BaseTheme-based theme is enabled.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-622)

**Comment by Piedone** [comment]
What do we need Helpful Widgets for?

**Comment by sarahelsaig** [comment]
The MenuWidget.

**Comment by Piedone** [comment]
Ah OK.
