### ISSUE TITLE
The main menu should populate from content items with MenuItemListPart (OSOE-623)

### ISSUE THREAD

**Issue by sarahelsaig** [Lombiq/Orchard-Base-Theme#66]
For example the Blog theme uses a Menu content type that contains `MenuItemListPart` to create its menu.

One way to do this is adding a new `INavigationProvider` that either looks for a content item with "main-menu" alias, or queries for `MenuItemListPart`. As far as I can see there is currently no index for this content part, so if we do the latter then an additional index provider would be good too.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-623)

**Comment by Piedone** [comment]
At that point, perhaps one would rather override the given shape and display the menu directly? Or are we talking about mixing multiple providers?

**Comment by sarahelsaig** [comment]
I was thinking of the latter. For example Lobiq.BaseTheme.Samples you'd want to merge it with the existing main menu navigation providers.

**Comment by Piedone** [comment]
Sounds good.
